cursor #ebe0dc
cursor_text_color #d6c3ba

foreground            #ebe0dc
background            #171210
selection_foreground  #402c21
selection_background  #e0c0b0
url_color             #f6b999

color0   #171210
color1   #ff7872
color2   #91f67b
color3   #ffe572
color4   #e9a47f
color5   #713e22
color6   #f6b999
color7   #fff5ef
color8   #9f9893
color9   #ffa39f
color10  #b6ffa5
color11  #ffeea5
color12  #ffc9ad
color13  #ffd2bb
color14  #ffe2d3
color15  #fffaf8
